### ISSUE TITLE
Images on Live Testing Page are not visible.

### ISSUE THREAD

**Issue by ardacebi** [Makeroid/docs#16]
Images don't appear even if the formatting is right in the live development page.

**Comment by conorshipp** [comment]
It doesn't look the images were uploaded to the repository.

**Comment by ardacebi** [comment]
@conorshipp but how? I uploaded all of them??

Wait, I will take care of it. I'm going to open a new pull request to a branch I'm going to create with all the images (same links so I won't need to change them again).

sorry :(

**Comment by ardacebi** [comment]
see this @conorshipp 
https://github.com/Makeroid/docs/pull/21
