### ISSUE TITLE
Screenshot component under Device category is not working

### ISSUE THREAD

**Issue by ardacebi** [Makeroid/docs#19]
Screenshot page is not working and not listed in gitbooks even if it's listed in the separate device page.

**Comment by ardacebi** [comment]
Any updates on this issue?

**Comment by conorshipp** [comment]
It looks fine for me. Which specific page are you referring to?

**Comment by barreeeiroo** [comment]
It's working for me

**Comment by ardacebi** [comment]
@conorshipp @barreeeiroo looks like this is an old issue. I've fixed it with a PR. Sorry, forgot closing the issue.
