### ISSUE TITLE
Old links in Builder

### ISSUE THREAD

**Issue by ardacebi** [Makeroid/docs#28]
Hello,
I've noticed that the "Learn More" links in the builder are old and not working. Let me give an example.

Let's look to the "Switch" component. When we click to the "Learn More" link, it will open the link below.

`https://docs.makeroid.io/components/user-interface/switchtoggle.html`

![pagenotfound](https://user-images.githubusercontent.com/17576065/35196269-c08813f8-fee0-11e7-80b5-c8d66c75072c.png)

but the right documentation link for the switch component is

`https://docs.makeroid.io/components/user-interface/switch.html`.

![switchdoc](https://user-images.githubusercontent.com/17576065/35196280-dcfd51ce-fee0-11e7-8631-8628a3993a67.png)

**Comment by barreeeiroo** [comment]
I can fix it by making redirects

**Comment by ardacebi** [comment]
@barreeeiroo fix them by making redirects. But as redirects are temporary solutions, I suggest you to change the links to their right form with the next builder update.

What do you think?

**Comment by barreeeiroo** [comment]
But that links are not fixed on the builder. They are created dynamically depending on components classes. I can't change that, and if I could change it then all apps would be broken as old AIAs wouldn't find their original components
That's why the unique solution is making redirects

**Comment by ardacebi** [comment]
OK, so make redirects. As I've completed all the white pages, users won't get an error or a blank page when they click on the link.

Anyways, the documentation is almost complete, this means in a few months, users will only see information!

**Comment by ardacebi** [comment]
@barreeeiroo when can you complete the redirects?

**Comment by barreeeiroo** [comment]
I'm doing now, missing only one category and committing

**Comment by ardacebi** [comment]
@barreeeiroo have you made the redirects? Looks like they still output a 404.
